### ISSUE TITLE
Think about recommendation of Catch2 as it is approaching v3

### ISSUE THREAD

**Issue by dokempf** [ssciwr/cookiecutter-cpp-project#32]
Catch will have a major release upcoming: https://github.com/catchorg/Catch2/blob/devel/docs/migrate-v2-to-v3.md

As I would like our recommendations as future-proof as possible, we should think about what to recommend.

**Comment by lkeegan** [comment]
For simple projects (e.g. https://github.com/ssciwr/cpp-project-template/) I would recommend simply including catch2 as a single header directly in the repo: it just works, avoids having to use submodules or requiring the user to install it, etc.

For larger projects (e.g. https://github.com/spatial-model-editor/spatial-model-editor) using v3 as an external library does reduce the test compile times

**Comment by dokempf** [comment]
Thinking about it, I think the cookiecutter can be left as is.
