### ISSUE TITLE
long_description from README

### ISSUE THREAD

**Issue by dokempf** [ssciwr/cookiecutter-cpp-project#81]
We have a current CI failure: https://github.com/dokempf/test-github-actions-cookiecutter-cpp-project/runs/6683691143?check_suite_focus=true

I think it is caused by a quite recent `pip` interpreting the empty string as faulty `rst`. Instead, we should use the README as long description and set its content type properly.

**Comment by lkeegan** [comment]
working example: https://github.com/spatial-model-editor/sme-contrib/blob/main/setup.py

**Comment by dokempf** [comment]
An alternative would be to switch to `setup.cfg` which supports this quite nicely: https://github.com/ssciwr/afwizard/blob/main/setup.cfg#L5 Also, it is capable of this which I really like: https://github.com/ssciwr/afwizard/blob/main/setup.cfg#L3

**Comment by lkeegan** [comment]
Agree that would be a better fix!
